### ISSUE TITLE
NeuralVDB implementation?

### ISSUE THREAD

**Issue by davoodkharmanzar** [eidosmontreal/unreal-vdb#31]
hi dear,

does a plan to implementing **[NeuralVDB](https://developer.nvidia.com/rendering-technologies/neuralvdb)**?

thanks.

**Comment by thilamb** [comment]
Hi, I'm extremely excited by NeuralVDB because it solves a few problems that are crucial for real time rendering.

But the tech is not available yet (with no ETA as far as I know) and will probably be very experimental at first (and only Nvidia RTX compatible).

Don't expect anything soon, but I'll definitely keep an eye on it and integrate it when possible.
