### ISSUE TITLE
MRQ custom render pass ??

### ISSUE THREAD

**Issue by davoodkharmanzar** [eidosmontreal/unreal-vdb#53]
hey,
is it possible to define custom render pass on **Movie Render Queue** to render only **VDB Principled** volumes?
thanks.

![Screenshot 2022-12-13 220752](https://user-images.githubusercontent.com/10723167/207417906-89baf42f-c549-4b42-88f8-9c7ee66fdb2d.jpg)

**Comment by thilamb** [comment]
I'm not sure I can add a custom render pass but you can render only VDBs by using the option:
```
r.Vdb.DebugMode 1 (Radiance/RGB only) or
r.Vdb.DebugMode 2 (VDB Alpha only)
```

I've updated the [FAQ section](https://github.com/eidosmontreal/unreal-vdb/blob/main/HELPME.md#can-i-only-render-vdbs-using-the-movie-render-queue-mrq-) because a lot of people have asked me the same question.

**Comment by davoodkharmanzar** [comment]
thanks for your reply ...
**alpha only** option would be great if be able to define as pass :]

**Comment by thilamb** [comment]
I'll investigate a bit to see if I can add a custom pass but I doubt it. I'll close this issue until then. Thanks !
