### ISSUE TITLE
Separate density multiplier for temperature volume

### ISSUE THREAD

**Issue by TheDistiller** [eidosmontreal/unreal-vdb#55]
Could you add an additional shading parameter to control the density of the temperature volume separate from the density volume? At the moment when I'm using the density multiplier to increase the smoke density of an explosion, the fire is getting very dense and crunched. Thanks!

**Comment by thilamb** [comment]
I think you’re looking for the « blackbody temperature » and « blackbody intensity » that will give you control on the temperature volume rendering. Let me know how it goes.

**Comment by TheDistiller** [comment]
Here's an example. At density 10 the flames are looking good but the smoke is barely visible. Increasing the density multiplier to 50 helps to make the smoke more visible, but it also increases the density of the flames which were already dense enough at 10 and are now too crushed at 50.

![Explosion_Comp_01](https://user-images.githubusercontent.com/7162105/209205299-00fa4d9a-db37-418b-b6e7-5070a0a4b0b5.gif)

**Comment by thilamb** [comment]
Adding more density definitely adds more contrast and weight to the smoke in between the flames. Temperature doens't really have a notion of "density", it's just adding radiance to the smoke.

Unless you tell me you know a different and better paper or implementation, I'm afraid this is pretty standard and state of the art for a single scattering renderer. Multiple scattering would help getting more diffusion and get closer to your ideal but it's way too expensive in a realtime context.

I recommend adding a post process bloom to fake that.

**Comment by TheDistiller** [comment]
Maybe this makes it clearer. In redshift you have the ability to adjust/remap density and emission separately whereas in your material the "density multiplier" value affects both density and emission at the same time.

![RS_VolumeShader](https://user-images.githubusercontent.com/7162105/209376775-3a97c20a-8ed2-4d72-bfac-c5b3eb5842eb.png)

**Comment by TheDistiller** [comment]
This plugin gives amazing results for smoke! For fire, to have finer control over the look, it'd be nice to be able to switch to a color ramp option in addition to the blackbody. Makes it easier to get exactly the look you want as shown in this example in Houdini:

![Houdini_Color_Ramp](https://user-images.githubusercontent.com/7162105/209474392-8b066530-b9a2-4d6f-b695-1190d821bdd6.png)

**Comment by thilamb** [comment]
Hi thanks and sorry for the delayed answer.

Adding a ramp is definitely doable and a good idea. Right now I'm using Unreal's predefined (and cheap) internal ramp. I'll try to do it next week.

As for your Redshift range/remap, it's not going to help with the issue. In most cases Min stays at 0 which means the remap is simply a multiplication, and that what's already available with the plugin.

**Comment by TheDistiller** [comment]
Hey, no worries.
Thanks for implementing the ramp! About the multiplication, my point has always just been to be able to control the smoke and fire individually rather than "density multiplier" controlling both at the same time. That's all.

**Comment by davoodkharmanzar** [comment]
i think we needs effective methods ... something like this maybe??   :]
https://twitter.com/OverdrawXYZ/status/1608614804851404800

**Comment by thilamb** [comment]
The color ramp (aka color curve/atlas) is already available in the github repo, and will be available soon in an official release:
https://user-images.githubusercontent.com/7030046/210806621-d2cd4ce5-bf3e-4cdc-a19a-d5d649d4c828.mp4

Please refer to [the official documentation](https://docs.unrealengine.com/5.1/en-US/curve-atlases-in-unreal-engine-materials/) if you need to know how Curve Atlases work.

**Comment by thilamb** [comment]
And final recap on the density vs temperature multiplier:

VDB Density values can be controlled (multiplied) with the "Density Multiplier" option.
VDB Temperature values can be controlled (multiplied) with the "Blackbody Temperature" option.

I could add a range remap like your Redshift example (it is easy to do) but I don't think it would add much compared to a simple multiplication, considering you probably don't want to mess with the "start range"  options. And the plugin is already complicated as it is, I don't want to introduce another difficulty.

To finish, every DCC is different and treats volumetric data differently, but the general rule is:
- VDB density values are not bounded but are usually between 0 and 1.
- VDB temperatures are usually normalized between 0 and 1. Their real Kelvin values are divided by the maximum temperature of the simulation. Hence the parameter "Blackbody temperature (in Kelvin)" which is supposed to match that maximum temperature from the simulations.

The new color ramp works only if temperature values are between 0 and 1 (like they should). To help control the curve I've added a "Temperature multiplier" to help rescale values in an artist-friendly way. It is the exact same multiplication as "blackbody temperature" but because one is physically based and the other isn't their ranges are way different, and I thought it would be much easier to understand and work with.

**Comment by thilamb** [comment]
Available with the [latest release](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.3_ue5.1.0).

I'll close this issue but feel free to re-open it if you are not satisfied (or open another issue).

Thanks for your feedback !
