### ISSUE TITLE
5.1.1 Packaging Error

### ISSUE THREAD

**Issue by azjata** [eidosmontreal/unreal-vdb#62]
Plugin works correctly in the editor. When packaging for Windows the project does not package.

Enabled r.ShaderDevelopment in the ConsoleVariables. Attaching the Error Log

![image](https://user-images.githubusercontent.com/483924/218994694-e2f437e1-d2da-4965-8ad5-ed10980ef550.png)

**Comment by thilamb** [comment]
Hello,

I fixed a similar issue in version 0.6.5.

Could you please confirm if you still have this issue with 0.6.5 ?

**Comment by thilamb** [comment]
If you're not using VdbPrincipledActors (you're probably not since you're trying to package a game), I have this ugly hack to temporarily help you:

Open file: `<wherever your vdb plugin is>\Plugins\SparseVolumetrics\Shaders\Private\VdbPrincipled.usf`
Change line 339 from 
`float4 Radiance = VdbFogVolume(uint2(SvPosition.xy)); `
to 
`float4 Radiance = 0.0;//VdbFogVolume(uint2(SvPosition.xy));`

**Comment by azjata** [comment]
the issue is still occuring in 0.6.5 although the "ugly hack" allows me to package without throwing the error, so that workaround works fine

**Comment by thilamb** [comment]
I [update the plugin](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.6_ue5.1.1) with a tentative fix. Hopefully it will help (without the ugly hack). Let me know.
