### ISSUE TITLE
Vdb Is it a heavy format to read if I use it for video games?

### ISSUE THREAD

**Issue by Sharkblack3D** [eidosmontreal/unreal-vdb#64]
Hi,
I started working with Embergen to create visual effects, and I would like to know if the VDB format is suitable for a video game. When I play the scene with 2 material actors, the FX have a hard time loading and I get lag.
Thanks in advance for your help

**Comment by thilamb** [comment]
Hi,

It's not a surprise that making realtime video games is extremely challenging and only possible through intense optimization and extreme care. A lot of techniques are only approximations, making games run in realtime albeit being less visually impressive than movies.

It is entirely up to you to decide how much frame budget you want to allocate on your renderer and on your volumetrics. It could be from 1 millisecond to 10 milliseconds if volumetrics are a strong focus for your game, but you will have to cut some other techniques elsewhere.

Volumetrics are **notoriously really expensive to render**, you just have to take this into account. Do you really want volumetrics in your game or can you replace them by standard approximations techniques like flipbooks ? Entirely up to you. Do you target a 30fps or 60fps or 120fps game ? Up to you. Do you want to use small volumes or very large volumes ? Up to you. Everything comes at a cost, you just have to plan for it.

Good luck ! Feel free to open a "Discussion" rather than a "Issue", or you can reach out on Twitter or Discord if you want to tlak more.

PS: This plugin is **really experimental**, you can't make a game with it yet unless you want to implement the rest of the features yourself.
