### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by mszawdyn** [eidosmontreal/unreal-vdb#68]
Sorry, I don't know if this it a right place to ask. I wonder about getting shadows on my vdbs. I noticed that checking on "Improved Skylight Sampling" brought self shadows on vdb. But only when Directional Light is enabled. If its not VDB emits light. Could you tell me what is correct way to deal with VDB shadows, both self shadows and the ones casted, for example on a ground?

**Comment by thilamb** [comment]
Sadly, with this plugin [VDBs do not receive or cast shadows](https://github.com/eidosmontreal/unreal-vdb/blob/main/HELPME.md#can-my-vdbs-receive-shadows--can-my-vdbs-cast-shadows-on-the-environment-) because of plugin limitations.

It's also [only using the first directional light](https://github.com/eidosmontreal/unreal-vdb/blob/main/HELPME.md#why-is-my-point-light-or-any-other-lights-not-affecting-the-vdbs-) for similar reasons.

You can fake shadows with opaque proxy object if you really need to but that's outside of the plugin support. 

Good luck !
