### ISSUE TITLE
Transparency sorting issue

### ISSUE THREAD

**Issue by SethPDA** [eidosmontreal/unreal-vdb#71]
Placing a translucent object behind the vdb makes it visible in front of it. Translucency sorting doesn't work with current version. Will this be fixed? I know that sorting translucent objects is not that easy, but I wrote a raymarcher that uses the translucent material domain and that way, the engine can sort it correctly (or at least how all translucent objects sort). I presume this doesn't work correctly because it uses a volume material domain but I may be wrong.

**Comment by Andrej730** [comment]
https://github.com/eidosmontreal/unreal-vdb/issues/48#issuecomment-1345471648

**Comment by thilamb** [comment]
Sadly this will not be fixed in the current plugin. I know it's annoying and I do apologize about it.

VDBs are very different so I need to use a custom render pass to render them, making all translucency sorting very difficult. They are either rendered before transparents or after transparents (and they both have issues). 

I'll close the issue but will be happy to discuss about it or anything else if you have more questions.
